baseURL = "https://gohugo.io"
title = "Hugo Theme Tailwind Example Site"
copyright = "Jacob Jeffries"
pagination.pagerSize = 3 # for demonstration of pagination
languageCode = "en"
defaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
theme = "tailwind"
enableGitInfo = true

[markup]
  _merge = "deep"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
