baseURL = "https://jwjeffr.github.io/recipes"
title = "My cooking blog!"
copyright = "Jacob Jeffries"
pagination.pagerSize = 3 # for demonstration of pagination
languageCode = "en"
defaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
theme = "hugo-theme-tailwind"
enableGitInfo = true

[markup]
  _merge = "deep"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
