# SEO keywords and description for your site.
keywords = "cooking, recipes"
subtitle = "Jacob Jeffries"
favicon = "https://github.com/jwjeffr/recipes/raw/refs/heads/main/static/favicon.ico"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "post"

jsonLD = true

showAuthor = true

[author]
  name = "Jacob Jeffries"
  email = "jwjeffries2000@gmail.com"

[header]
  logo = "https://github.com/jwjeffr/recipes/raw/refs/heads/main/static/icon.png"
  title = "Cooking Blog"

[footer]
  since = 2025
  poweredby = true

[pwa]
  enabled = true
  icon = "https://github.com/jwjeffr/recipes/raw/refs/heads/main/static/icon.png" # should be in assets
  icon_sizes = [192, 512]

  [manifest]
  description = "My personal cooking blog"
